# Generated by Django 4.2.20 on 2025-05-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBotao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonfield', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoMachine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('dia_e_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.IntegerField(verbose_name='Temperatura')),
            ],
            options={
                'verbose_name': 'Dados Produção Machine 1',
                'verbose_name_plural': 'Produção Machine 1',
            },
        ),
    ]
