# Generated by Django 4.2.20 on 2025-03-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadobotao',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
