# Generated by Django 4.2.20 on 2025-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupMachine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_setup_le', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempo_setup_le', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_setup_ld', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempo_setup_ld', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setup Machine 1',
                'verbose_name_plural': 'Setup Machine 1',
                'ordering': ['-criado'],
            },
        ),
    ]
