# Generated by Django 4.2.20 on 2025-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setupmachine1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoDunexa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('pessoas', models.IntegerField()),
                ('carros', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dados de Monitoramento',
                'verbose_name_plural': 'Dados de Monitoramento',
                'ordering': ['-criado'],
            },
        ),
        migrations.AlterField(
            model_name='setupmachine1',
            name='temperatura_setup_le',
            field=models.DecimalField(decimal_places=2, help_text='Celcius', max_digits=5),
        ),
        migrations.AlterField(
            model_name='setupmachine1',
            name='tempo_setup_le',
            field=models.DecimalField(decimal_places=2, help_text='Segundos', max_digits=5),
        ),
    ]
