# Generated by Django 4.2.20 on 2025-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estadobotao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadobotao',
            name='horario',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
