# Generated by Django 4.2.20 on 2025-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testerest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerest',
            name='temperatura',
            field=models.IntegerField(verbose_name='Tempêratura'),
        ),
    ]
