# Generated by Django 4.2.20 on 2025-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estadobotao_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadobotao',
            name='estado',
            field=models.IntegerField(),
        ),
    ]
